language: java
jdk:
  - oraclejdk7
notifications:
  email: false
before_script:
 - chmod +x init.sh
install:
  - ./init.sh
  - mvn clean package
deploy:
    provider: releases
    api-key: "$GITHUB_OATH_TOKEN"
    file:
        - "target/UntamedChat.jar"
    skip_cleanup: true
    on:
        tags: true
        all_branches: true